spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/dep_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082